### PR TITLE
Incluide data from all modules automatically

### PR DESCRIPTION
**Pull request by maxencelaurent**
Just spent some time on the extension to include data from all modules.

Main improvements:
* display all modules in the popup menu, including battery status and refresh date image

   * unreachable modules have n/a date and unknown battery state: image
* measures are displayed according to user preferences
   * trend are shown as line going up, down or to the right (stable)
   * wind directions are converted from degree to compass direction
* related measures are grouped
   * eg for temperatures: current temp and trend on the first line, then min_temp and date_min_temp on an indented new line, same for max_temp 
image

Here is a full screenshot:

image

I did not change anything about the configuration nor the content of the panel button.

### CODE REVIEW

**Comment by profy12** [comment]
Sorry I missed the notification, i will try to merge your request asap.

**Comment by maxencelaurent** [comment]
Thanks

I just remember I made some minor improvements,,, But dit not commit them...

**Comment by profy12** [comment]
you can, I will test and make a new release.

**Comment by profy12** [comment]
Your code is released in version 4, thanks !

**Pull request merged**
