### PR TITLE
Migrate to gnome 40

### PR DESCRIPTION
**Pull request by maxencelaurent**
Gnome 40 introduces breaking changes. Among others, preference panel must now use gtk-4.
This pull request address this issue.

=> Update major version to 5.

### CODE REVIEW

**Comment by SvenAbels** [comment]
@maxencelaurent   It looks like this project is unmaintained. How can I apply your fixes so that I can use the extension in gnome again?

**Comment by maxencelaurent** [comment]
Hey @SvenAbels,

first, you need to clone my fork somewhere in your home (~/usr/src/ for instance)
```bash
cd ~/usr/src/
git clone https://github.com/maxencelaurent/gnome-shell-netatmo-station.git
```

Then you have to install the extensions manually by creating a link to the git reposition in your "~/.local/share/gnome-shell/extensions" folder

```bash
cd ~/.local/share/gnome-shell/extensions/
ln -s  ~/usr/src/gnome-shell-netatmo-station netatmo-station@aurelien.bras.gmail.com
```

Finally, you have to log out and log back in.

**Comment by SvenAbels** [comment]
@maxencelaurent: Great. Thanks a lot :-)

**Comment by profy12** [comment]
Hello, sorry for the late and thanks @maxencelaurent. I will release new version soon.

**Pull request merged**
